using System.Data.Common;
using Npgsql;
using RepoDb;
using RepoDb.Interfaces;
using UnitOfWork.Core;
using UnitOfWork.RepoDb.ProviderTests.Shared;

namespace UnitOfWork.RepoDb.PostgreSql.Tests;

internal sealed class PostgreSqlProviderHarness : IRepoDbProviderHarness
{
    private readonly string _connectionString =
        Environment.GetEnvironmentVariable("UOW_TEST_POSTGRESQL")
        ?? throw new InvalidOperationException("UOW_TEST_POSTGRESQL is not set.");

    public string ProviderName => "PostgreSQL";

    public string ScalarOneSql => "SELECT 1;";

    public IDbHelper GetOfficialHelper()
    {
        GlobalConfiguration.Setup().UsePostgreSql();
        return DbHelperMapper.Get<NpgsqlConnection>();
    }

    public void RegisterMappings(IDbHelper helper)
    {
        GlobalConfiguration.Setup().UsePostgreSql();
        DbSettingMapper.Add<TransactionBoundDbConnection>(
            DbSettingMapper.Get<NpgsqlConnection>(),
            true);
        DbHelperMapper.Add<TransactionBoundDbConnection>(helper, true);
        StatementBuilderMapper.Add<TransactionBoundDbConnection>(
            StatementBuilderMapper.Get<NpgsqlConnection>(),
            true);
    }

    public IDbConnectionFactory CreateConnectionFactory() =>
        new PostgreSqlConnectionFactory(_connectionString);

    public async Task ResetSchemaAsync(CancellationToken cancellationToken = default)
    {
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);
        await ExecuteAsync(connection, "DROP TABLE IF EXISTS counter_archive;", cancellationToken);
        await ExecuteAsync(connection, "DROP TABLE IF EXISTS counter;", cancellationToken);
        await ExecuteAsync(connection,
            "CREATE TABLE counter (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value INTEGER NOT NULL);",
            cancellationToken);
        await ExecuteAsync(connection,
            "CREATE TABLE counter_archive (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value INTEGER NOT NULL);",
            cancellationToken);
    }

    public async Task<long> CountRowsAsync(
        string tableName,
        CancellationToken cancellationToken = default)
    {
        var normalizedTable = NormalizeTableName(tableName);
        await using var connection = new NpgsqlConnection(_connectionString);
        await connection.OpenAsync(cancellationToken);
        await using var command = connection.CreateCommand();
        command.CommandText = $"SELECT COUNT(*) FROM {normalizedTable};";
        return Convert.ToInt64(await command.ExecuteScalarAsync(cancellationToken));
    }

    public ValueTask DisposeAsync() => ValueTask.CompletedTask;

    private static async Task ExecuteAsync(
        NpgsqlConnection connection,
        string sql,
        CancellationToken cancellationToken)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync(cancellationToken);
    }

    private static string NormalizeTableName(string tableName) => tableName switch
    {
        "counter" => "counter",
        "counter_archive" => "counter_archive",
        _ => throw new ArgumentOutOfRangeException(nameof(tableName), tableName, "Unknown test table.")
    };

    private sealed class PostgreSqlConnectionFactory : IDbConnectionFactory
    {
        private readonly string _connectionString;

        public PostgreSqlConnectionFactory(string connectionString)
        {
            _connectionString = connectionString;
        }

        public DbConnection CreateConnection() => new NpgsqlConnection(_connectionString);
    }
}
